fix(auth): SSO failed to get token due to missing 'refreshToken' (#6234)
## Problem:

Error users were seeing was:

```
Error: SSO cache data unexpectedly missing props: ["refreshToken"]
```

This was due to a change from a previous PR that assumed the
refreshToken was always present in SSO cache.

## Solution:

It looks like the refreshToken does not exist for all cases, so some
research needs to be done.

But for now this reverts the validation that the refreshToken exists.
Though it keeps the validation that the accessToken exists since that is
always guaranteed.

**A temporary workaround should be to sign out/in and things should
start working. If not please downgrade 3.38.0 until we release this fix
next week.**

Fixes #6230 

---

- Treat all work as PUBLIC. Private `feature/x` branches will not be
squash-merged at release time.
- Your code changes must meet the guidelines in
[CONTRIBUTING.md](https://github.com/aws/aws-toolkit-vscode/blob/master/CONTRIBUTING.md#guidelines).

License: I confirm that my contribution is made under the terms of the
Apache 2.0 license.

---------

Signed-off-by: nkomonen-amazon <nkomonen@amazon.com>